# Use an official Node.js runtime as a parent image
FROM node:22 AS build

# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json into the container
COPY package*.json ./

# Install the application dependencies
RUN npm install

# Copy the application code into the container
COPY . .

# Build the React application for production
RUN npm run build

# Use an official nginx image as the base image for serving the application
FROM nginx:alpine

# Copy the build output to the nginx html directory
COPY --from=build /app/build /usr/share/nginx/html

# Copy custom nginx configuration file
COPY nginx.conf /etc/nginx/nginx.conf

# Expose port 3000 to the outside world
EXPOSE 3000

# Start nginx when the container launches
CMD ["nginx", "-g", "daemon off;"]
