FROM python:3.13-rc-slim

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
WORKDIR /app
RUN apt-get update \
    && apt-get install -y build-essential libpq-dev \
    && apt-get clean
COPY requirements.txt /app/
RUN pip install --upgrade pip \
    && pip install -r requirements.txt
COPY . /app/
EXPOSE 8000
CMD ["sh", "-c", "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"]

